Update cloudbuild.yaml

diff --git a/cloudbuild/cloudbuild.yaml b/cloudbuild/cloudbuild.yaml
--- a/cloudbuild/cloudbuild.yaml
+++ b/cloudbuild/cloudbuild.yaml
@@ -12,10 +12,9 @@ steps:
       - |
         npm install
         npm run test
-  - name: 'gcr.io/cloud-builders/git'
-    entrypoint: 'bash'
-    args:
-      - '-c'
-      - |
-        echo 'PASSED'
+        if [ $? -eq 0 ]; then
+          echo "All tests passed successfully";
+        else
+          echo "One or more tests failed";
+        fi
 timeout: 660s
